baseURL = "http://computational-humanities-research/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Computational Humanities Research"
theme = "chr"
publishDir = "docs"

[params]
  customCSS = ["css/custom.css"]
  short = "CHR"

[menu]

  [[menu.main]]
      identifier = "about"
      name = "About"
      url = "/about"
      weight = -2000

   [[menu.main]]
      identifier = "news"
      name = "News"
      url = "/news"
      weight = -1850

   [[menu.main]]
      identifier = "Confeence"
      name = "Conference"
      url = "/conference"
      weight = -1750

  [[menu.main]]
     identifier = "journal"
     name = "Journal"
     url = "/journal"
     weight = -1500
    
  [[menu.main]]
      identifier = "Board"
      name = "Board"
      url = "/Board"
      weight = -1000

[markup.goldmark.renderer]
unsafe = true
